/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2024-12-06 15:09:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/ADMIN/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1729394088156L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"refresh\" content=\"1;url=main_web.html\">\r\n");
      out.write("    <title>THE LIEMS IELTS CENTER</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            background: #f0bc4229;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* From Uiverse.io by Nawsome */\r\n");
      out.write("        .wheel-and-hamster {\r\n");
      out.write("            --dur: 1s;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            width: 12em;\r\n");
      out.write("            height: 12em;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .wheel,\r\n");
      out.write("        .hamster,\r\n");
      out.write("        .hamster div,\r\n");
      out.write("        .spoke {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .wheel,\r\n");
      out.write("        .spoke {\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .wheel {\r\n");
      out.write("            background: radial-gradient(100% 100% at center,hsla(0,0%,60%,0) 47.8%,hsl(0,0%,60%) 48%);\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hamster {\r\n");
      out.write("            animation: hamster var(--dur) ease-in-out infinite;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            left: calc(50% - 3.5em);\r\n");
      out.write("            width: 7em;\r\n");
      out.write("            height: 3.75em;\r\n");
      out.write("            transform: rotate(4deg) translate(-0.8em,1.85em);\r\n");
      out.write("            transform-origin: 50% 0;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hamster__head {\r\n");
      out.write("            animation: hamsterHead var(--dur) ease-in-out infinite;\r\n");
      out.write("            background: hsl(30,90%,55%);\r\n");
      out.write("            border-radius: 70% 30% 0 100% / 40% 25% 25% 60%;\r\n");
      out.write("            box-shadow: 0 -0.25em 0 hsl(30,90%,80%) inset,\r\n");
      out.write("                    0.75em -1.55em 0 hsl(30,90%,90%) inset;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: -2em;\r\n");
      out.write("            width: 2.75em;\r\n");
      out.write("            height: 2.5em;\r\n");
      out.write("            transform-origin: 100% 50%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hamster__ear {\r\n");
      out.write("            animation: hamsterEar var(--dur) ease-in-out infinite;\r\n");
      out.write("            background: hsl(0,90%,85%);\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            box-shadow: -0.25em 0 hsl(30,90%,55%) inset;\r\n");
      out.write("            top: -0.25em;\r\n");
      out.write("            right: -0.25em;\r\n");
      out.write("            width: 0.75em;\r\n");
      out.write("            height: 0.75em;\r\n");
      out.write("            transform-origin: 50% 75%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hamster__eye {\r\n");
      out.write("            animation: hamsterEye var(--dur) linear infinite;\r\n");
      out.write("            background-color: hsl(0,0%,0%);\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            top: 0.375em;\r\n");
      out.write("            left: 1.25em;\r\n");
      out.write("            width: 0.5em;\r\n");
      out.write("            height: 0.5em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hamster__nose {\r\n");
      out.write("            background: hsl(0,90%,75%);\r\n");
      out.write("            border-radius: 35% 65% 85% 15% / 70% 50% 50% 30%;\r\n");
      out.write("            top: 0.75em;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 0.2em;\r\n");
      out.write("            height: 0.25em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hamster__body {\r\n");
      out.write("            animation: hamsterBody var(--dur) ease-in-out infinite;\r\n");
      out.write("            background: hsl(30,90%,90%);\r\n");
      out.write("            border-radius: 50% 30% 50% 30% / 15% 60% 40% 40%;\r\n");
      out.write("            box-shadow: 0.1em 0.75em 0 hsl(30,90%,55%) inset,\r\n");
      out.write("                    0.15em -0.5em 0 hsl(30,90%,80%) inset;\r\n");
      out.write("            top: 0.25em;\r\n");
      out.write("            left: 2em;\r\n");
      out.write("            width: 4.5em;\r\n");
      out.write("            height: 3em;\r\n");
      out.write("            transform-origin: 17% 50%;\r\n");
      out.write("            transform-style: preserve-3d;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hamster__limb--fr,\r\n");
      out.write("        .hamster__limb--fl {\r\n");
      out.write("            clip-path: polygon(0 0,100% 0,70% 80%,60% 100%,0% 100%,40% 80%);\r\n");
      out.write("            top: 2em;\r\n");
      out.write("            left: 0.5em;\r\n");
      out.write("            width: 1em;\r\n");
      out.write("            height: 1.5em;\r\n");
      out.write("            transform-origin: 50% 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hamster__limb--fr {\r\n");
      out.write("            animation: hamsterFRLimb var(--dur) linear infinite;\r\n");
      out.write("            background: linear-gradient(hsl(30,90%,80%) 80%,hsl(0,90%,75%) 80%);\r\n");
      out.write("            transform: rotate(15deg) translateZ(-1px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hamster__limb--fl {\r\n");
      out.write("            animation: hamsterFLLimb var(--dur) linear infinite;\r\n");
      out.write("            background: linear-gradient(hsl(30,90%,90%) 80%,hsl(0,90%,85%) 80%);\r\n");
      out.write("            transform: rotate(15deg);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hamster__limb--br,\r\n");
      out.write("        .hamster__limb--bl {\r\n");
      out.write("            border-radius: 0.75em 0.75em 0 0;\r\n");
      out.write("            clip-path: polygon(0 0,100% 0,100% 30%,70% 90%,70% 100%,30% 100%,40% 90%,0% 30%);\r\n");
      out.write("            top: 1em;\r\n");
      out.write("            left: 2.8em;\r\n");
      out.write("            width: 1.5em;\r\n");
      out.write("            height: 2.5em;\r\n");
      out.write("            transform-origin: 50% 30%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hamster__limb--br {\r\n");
      out.write("            animation: hamsterBRLimb var(--dur) linear infinite;\r\n");
      out.write("            background: linear-gradient(hsl(30,90%,80%) 90%,hsl(0,90%,75%) 90%);\r\n");
      out.write("            transform: rotate(-25deg) translateZ(-1px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hamster__limb--bl {\r\n");
      out.write("            animation: hamsterBLLimb var(--dur) linear infinite;\r\n");
      out.write("            background: linear-gradient(hsl(30,90%,90%) 90%,hsl(0,90%,85%) 90%);\r\n");
      out.write("            transform: rotate(-25deg);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hamster__tail {\r\n");
      out.write("            animation: hamsterTail var(--dur) linear infinite;\r\n");
      out.write("            background: hsl(0,90%,85%);\r\n");
      out.write("            border-radius: 0.25em 50% 50% 0.25em;\r\n");
      out.write("            box-shadow: 0 -0.2em 0 hsl(0,90%,75%) inset;\r\n");
      out.write("            top: 1.5em;\r\n");
      out.write("            right: -0.5em;\r\n");
      out.write("            width: 1em;\r\n");
      out.write("            height: 0.5em;\r\n");
      out.write("            transform: rotate(30deg) translateZ(-1px);\r\n");
      out.write("            transform-origin: 0.25em 0.25em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .spoke {\r\n");
      out.write("            animation: spoke var(--dur) linear infinite;\r\n");
      out.write("            background: radial-gradient(100% 100% at center,hsl(0,0%,60%) 4.8%,hsla(0,0%,60%,0) 5%),\r\n");
      out.write("                    linear-gradient(hsla(0,0%,55%,0) 46.9%,hsl(0,0%,65%) 47% 52.9%,hsla(0,0%,65%,0) 53%) 50% 50% / 99% 99% no-repeat;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animations */\r\n");
      out.write("        @keyframes hamster {\r\n");
      out.write("            from, to {\r\n");
      out.write("                transform: rotate(4deg) translate(-0.8em,1.85em);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            50% {\r\n");
      out.write("                transform: rotate(0) translate(-0.8em,1.85em);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes hamsterHead {\r\n");
      out.write("            from, 25%, 50%, 75%, to {\r\n");
      out.write("                transform: rotate(0);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            12.5%, 37.5%, 62.5%, 87.5% {\r\n");
      out.write("                transform: rotate(8deg);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes hamsterEye {\r\n");
      out.write("            from, 90%, to {\r\n");
      out.write("                transform: scaleY(1);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            95% {\r\n");
      out.write("                transform: scaleY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes hamsterEar {\r\n");
      out.write("            from, 25%, 50%, 75%, to {\r\n");
      out.write("                transform: rotate(0);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            12.5%, 37.5%, 62.5%, 87.5% {\r\n");
      out.write("                transform: rotate(12deg);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes hamsterBody {\r\n");
      out.write("            from, 25%, 50%, 75%, to {\r\n");
      out.write("                transform: rotate(0);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            12.5%, 37.5%, 62.5%, 87.5% {\r\n");
      out.write("                transform: rotate(-2deg);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes hamsterFRLimb {\r\n");
      out.write("            from, 25%, 50%, 75%, to {\r\n");
      out.write("                transform: rotate(50deg) translateZ(-1px);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            12.5%, 37.5%, 62.5%, 87.5% {\r\n");
      out.write("                transform: rotate(-30deg) translateZ(-1px);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes hamsterFLLimb {\r\n");
      out.write("            from, 25%, 50%, 75%, to {\r\n");
      out.write("                transform: rotate(-30deg);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            12.5%, 37.5%, 62.5%, 87.5% {\r\n");
      out.write("                transform: rotate(50deg);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes hamsterBRLimb {\r\n");
      out.write("            from, 25%, 50%, 75%, to {\r\n");
      out.write("                transform: rotate(-60deg) translateZ(-1px);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            12.5%, 37.5%, 62.5%, 87.5% {\r\n");
      out.write("                transform: rotate(20deg) translateZ(-1px);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes hamsterBLLimb {\r\n");
      out.write("            from, 25%, 50%, 75%, to {\r\n");
      out.write("                transform: rotate(20deg);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            12.5%, 37.5%, 62.5%, 87.5% {\r\n");
      out.write("                transform: rotate(-60deg);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes hamsterTail {\r\n");
      out.write("            from, 25%, 50%, 75%, to {\r\n");
      out.write("                transform: rotate(30deg) translateZ(-1px);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            12.5%, 37.5%, 62.5%, 87.5% {\r\n");
      out.write("                transform: rotate(10deg) translateZ(-1px);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes spoke {\r\n");
      out.write("            from {\r\n");
      out.write("                transform: rotate(0);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            to {\r\n");
      out.write("                transform: rotate(-1turn);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <div aria-label=\"Orange and tan hamster running in a metal wheel\" role=\"img\" class=\"wheel-and-hamster\">\r\n");
      out.write("        <div class=\"wheel\"></div>\r\n");
      out.write("        <div class=\"hamster\">\r\n");
      out.write("            <div class=\"hamster__body\">\r\n");
      out.write("                <div class=\"hamster__head\">\r\n");
      out.write("                    <div class=\"hamster__ear\"></div>\r\n");
      out.write("                    <div class=\"hamster__eye\"></div>\r\n");
      out.write("                    <div class=\"hamster__nose\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"hamster__limb hamster__limb--fr\"></div>\r\n");
      out.write("                <div class=\"hamster__limb hamster__limb--fl\"></div>\r\n");
      out.write("                <div class=\"hamster__limb hamster__limb--br\"></div>\r\n");
      out.write("                <div class=\"hamster__limb hamster__limb--bl\"></div>\r\n");
      out.write("                <div class=\"hamster__tail\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"spoke\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
